/**
 * Token Transformer
 *
 * Transforms design tokens into multiple output formats:
 * CSS, SCSS, JavaScript, JSON, Figma, Tailwind, iOS, Android
 */

import type {
  DesignToken,
  TokenCollection,
  TokenFormat,
  TokenCategory,
  ColorScheme,
} from './designTokens';
import { getTokenPath, tokenToCssVarName } from './designTokens';

// =============================================================================
// TRANSFORMER OPTIONS
// =============================================================================

export interface TransformOptions {
  format: TokenFormat;
  colorScheme?: ColorScheme;
  includeMeta?: boolean;
  prefix?: string;
  indent?: string;
  outputMode?: 'flat' | 'nested';
  categories?: TokenCategory[];
}

export interface TransformResult {
  format: TokenFormat;
  content: string;
  filename: string;
  mimeType: string;
}

// =============================================================================
// CSS TRANSFORMER
// =============================================================================

function transformToCSS(
  tokens: DesignToken[],
  options: TransformOptions
): TransformResult {
  const { colorScheme = 'light', prefix = '', indent = '  ' } = options;
  const lines: string[] = [];

  // Group tokens by path for better organization
  const groupedTokens = groupTokensByPath(tokens);

  lines.push(':root {');

  for (const [path, pathTokens] of Object.entries(groupedTokens)) {
    if (options.includeMeta) {
      lines.push(`${indent}/* ${path} */`);
    }

    for (const token of pathTokens) {
      const varName = prefix
        ? `--${prefix}-${token.path.join('-')}-${token.name}`
        : tokenToCssVarName(token);

      const value = colorScheme === 'dark' && token.value.darkValue
        ? token.value.darkValue
        : token.value.value;

      if (options.includeMeta && token.metadata?.description) {
        lines.push(`${indent}/* ${token.metadata.description} */`);
      }

      lines.push(`${indent}${varName}: ${value};`);
    }

    lines.push('');
  }

  lines.push('}');

  // Add dark mode variant
  if (colorScheme === 'light') {
    const darkTokens = tokens.filter(t => t.value.darkValue);
    if (darkTokens.length > 0) {
      lines.push('');
      lines.push('@media (prefers-color-scheme: dark) {');
      lines.push(`${indent}:root {`);

      for (const token of darkTokens) {
        const varName = prefix
          ? `--${prefix}-${token.path.join('-')}-${token.name}`
          : tokenToCssVarName(token);
        lines.push(`${indent}${indent}${varName}: ${token.value.darkValue};`);
      }

      lines.push(`${indent}}`);
      lines.push('}');

      // Also add .dark class variant
      lines.push('');
      lines.push('.dark {');

      for (const token of darkTokens) {
        const varName = prefix
          ? `--${prefix}-${token.path.join('-')}-${token.name}`
          : tokenToCssVarName(token);
        lines.push(`${indent}${varName}: ${token.value.darkValue};`);
      }

      lines.push('}');
    }
  }

  return {
    format: 'css',
    content: lines.join('\n'),
    filename: 'tokens.css',
    mimeType: 'text/css',
  };
}

// =============================================================================
// SCSS TRANSFORMER
// =============================================================================

function transformToSCSS(
  tokens: DesignToken[],
  options: TransformOptions
): TransformResult {
  const { colorScheme = 'light', prefix = '', includeMeta = false } = options;
  const lines: string[] = [];

  // SCSS variables
  lines.push('// Design Tokens - SCSS Variables');
  lines.push('// Generated by Tailwind Builder');
  lines.push('');

  const groupedTokens = groupTokensByPath(tokens);

  for (const [path, pathTokens] of Object.entries(groupedTokens)) {
    lines.push(`// ${path}`);

    for (const token of pathTokens) {
      const varName = prefix
        ? `$${prefix}-${token.path.join('-')}-${token.name}`
        : `$${token.path.join('-')}-${token.name}`;

      const value = colorScheme === 'dark' && token.value.darkValue
        ? token.value.darkValue
        : token.value.value;

      if (includeMeta && token.metadata?.description) {
        lines.push(`// ${token.metadata.description}`);
      }

      lines.push(`${varName}: ${value};`);
    }

    lines.push('');
  }

  // Add a map for easier access
  lines.push('// Token Maps');
  lines.push('$tokens: (');

  for (const [path, pathTokens] of Object.entries(groupedTokens)) {
    lines.push(`  "${path}": (`);
    for (const token of pathTokens) {
      const value = colorScheme === 'dark' && token.value.darkValue
        ? token.value.darkValue
        : token.value.value;
      lines.push(`    "${token.name}": ${value},`);
    }
    lines.push('  ),');
  }

  lines.push(');');

  // Add utility function
  lines.push('');
  lines.push('// Utility function to get token value');
  lines.push('@function token($path, $name) {');
  lines.push('  @if map-has-key($tokens, $path) {');
  lines.push('    $group: map-get($tokens, $path);');
  lines.push('    @if map-has-key($group, $name) {');
  lines.push('      @return map-get($group, $name);');
  lines.push('    }');
  lines.push('  }');
  lines.push('  @warn "Token not found: #{$path}/#{$name}";');
  lines.push('  @return null;');
  lines.push('}');

  return {
    format: 'scss',
    content: lines.join('\n'),
    filename: 'tokens.scss',
    mimeType: 'text/x-scss',
  };
}

// =============================================================================
// JAVASCRIPT/TYPESCRIPT TRANSFORMER
// =============================================================================

function transformToJS(
  tokens: DesignToken[],
  options: TransformOptions & { typescript?: boolean }
): TransformResult {
  const { colorScheme = 'light', prefix = '', typescript = false } = options;
  const lines: string[] = [];

  if (typescript) {
    lines.push('/**');
    lines.push(' * Design Tokens');
    lines.push(' * Generated by Tailwind Builder');
    lines.push(' */');
    lines.push('');
    lines.push('export interface TokenValue {');
    lines.push('  value: string;');
    lines.push('  darkValue?: string;');
    lines.push('}');
    lines.push('');
  }

  // Build nested object
  const tokenObj = buildNestedObject(tokens, colorScheme);

  const objName = prefix ? `${prefix}Tokens` : 'tokens';

  if (typescript) {
    lines.push(`export const ${objName} = ${JSON.stringify(tokenObj, null, 2)} as const;`);
    lines.push('');
    lines.push(`export type TokenPath = keyof typeof ${objName};`);
  } else {
    lines.push(`export const ${objName} = ${JSON.stringify(tokenObj, null, 2)};`);
  }

  lines.push('');

  // Add helper functions
  lines.push('/**');
  lines.push(' * Get token value by path');
  lines.push(' * @example getToken("color.primitive.blue.500")');
  lines.push(' */');

  if (typescript) {
    lines.push(`export function getToken(path: string): string | undefined {`);
  } else {
    lines.push(`export function getToken(path) {`);
  }

  lines.push(`  const parts = path.split('.');`);
  lines.push(`  let current = ${objName};`);
  lines.push('  for (const part of parts) {');
  lines.push('    if (current && typeof current === "object" && part in current) {');
  lines.push('      current = current[part];');
  lines.push('    } else {');
  lines.push('      return undefined;');
  lines.push('    }');
  lines.push('  }');
  lines.push('  return typeof current === "string" ? current : undefined;');
  lines.push('}');

  return {
    format: typescript ? 'ts' : 'js',
    content: lines.join('\n'),
    filename: typescript ? 'tokens.ts' : 'tokens.js',
    mimeType: typescript ? 'text/typescript' : 'text/javascript',
  };
}

// =============================================================================
// JSON TRANSFORMER (Style Dictionary Format)
// =============================================================================

function transformToJSON(
  tokens: DesignToken[],
  options: TransformOptions
): TransformResult {
  const { colorScheme = 'light', includeMeta = true } = options;

  const styleDictionaryTokens: Record<string, unknown> = {};

  for (const token of tokens) {
    let current = styleDictionaryTokens;

    // Navigate/create nested structure
    for (const part of token.path) {
      if (!current[part]) {
        current[part] = {};
      }
      current = current[part] as Record<string, unknown>;
    }

    // Add token
    const tokenData: Record<string, unknown> = {
      value: colorScheme === 'dark' && token.value.darkValue
        ? token.value.darkValue
        : token.value.value,
      type: token.type,
    };

    if (includeMeta) {
      if (token.metadata?.description) {
        tokenData.description = token.metadata.description;
      }
      if (token.reference) {
        tokenData.$reference = token.reference;
      }
      if (token.value.darkValue) {
        tokenData.$darkValue = token.value.darkValue;
      }
    }

    current[token.name] = tokenData;
  }

  return {
    format: 'json',
    content: JSON.stringify(styleDictionaryTokens, null, 2),
    filename: 'tokens.json',
    mimeType: 'application/json',
  };
}

// =============================================================================
// FIGMA TOKENS TRANSFORMER
// =============================================================================

function transformToFigma(
  tokens: DesignToken[],
  options: TransformOptions
): TransformResult {
  const { colorScheme = 'light' } = options;

  const figmaTokens: Record<string, unknown> = {
    global: {},
  };

  const global = figmaTokens.global as Record<string, unknown>;

  for (const token of tokens) {
    let current = global;

    // Create nested path
    for (const part of token.path) {
      if (!current[part]) {
        current[part] = {};
      }
      current = current[part] as Record<string, unknown>;
    }

    const value = colorScheme === 'dark' && token.value.darkValue
      ? token.value.darkValue
      : token.value.value;

    // Figma tokens format
    current[token.name] = {
      value,
      type: mapTypeToFigma(token.type),
      ...(token.metadata?.description && { description: token.metadata.description }),
    };
  }

  // Add dark mode as separate set if applicable
  const darkTokens = tokens.filter(t => t.value.darkValue);
  if (darkTokens.length > 0) {
    figmaTokens.dark = {};
    const dark = figmaTokens.dark as Record<string, unknown>;

    for (const token of darkTokens) {
      let current = dark;

      for (const part of token.path) {
        if (!current[part]) {
          current[part] = {};
        }
        current = current[part] as Record<string, unknown>;
      }

      current[token.name] = {
        value: token.value.darkValue,
        type: mapTypeToFigma(token.type),
      };
    }
  }

  return {
    format: 'figma',
    content: JSON.stringify(figmaTokens, null, 2),
    filename: 'figma-tokens.json',
    mimeType: 'application/json',
  };
}

// =============================================================================
// TAILWIND CONFIG TRANSFORMER
// =============================================================================

function transformToTailwind(
  tokens: DesignToken[],
  options: TransformOptions
): TransformResult {
  const { colorScheme = 'light' } = options;
  const lines: string[] = [];

  lines.push('/** @type {import("tailwindcss").Config} */');
  lines.push('module.exports = {');
  lines.push('  theme: {');
  lines.push('    extend: {');

  // Colors
  const colorTokens = tokens.filter(t => t.category === 'color');
  if (colorTokens.length > 0) {
    lines.push('      colors: {');
    const colorObj = buildColorObject(colorTokens, colorScheme);
    lines.push(formatObjectContent(colorObj, 8));
    lines.push('      },');
  }

  // Spacing
  const spacingTokens = tokens.filter(t => t.category === 'spacing');
  if (spacingTokens.length > 0) {
    lines.push('      spacing: {');
    for (const token of spacingTokens) {
      const key = token.name.replace('spacing-', '');
      lines.push(`        '${key}': '${token.value.value}',`);
    }
    lines.push('      },');
  }

  // Font Size
  const fontSizeTokens = tokens.filter(t => t.type === 'fontSize');
  if (fontSizeTokens.length > 0) {
    lines.push('      fontSize: {');
    for (const token of fontSizeTokens) {
      const key = token.name.replace('font-size-', '');
      lines.push(`        '${key}': '${token.value.value}',`);
    }
    lines.push('      },');
  }

  // Font Weight
  const fontWeightTokens = tokens.filter(t => t.type === 'fontWeight');
  if (fontWeightTokens.length > 0) {
    lines.push('      fontWeight: {');
    for (const token of fontWeightTokens) {
      const key = token.name.replace('font-weight-', '');
      lines.push(`        '${key}': '${token.value.value}',`);
    }
    lines.push('      },');
  }

  // Border Radius
  const radiusTokens = tokens.filter(t => t.type === 'borderRadius');
  if (radiusTokens.length > 0) {
    lines.push('      borderRadius: {');
    for (const token of radiusTokens) {
      const key = token.name.replace('border-radius-', '');
      lines.push(`        '${key}': '${token.value.value}',`);
    }
    lines.push('      },');
  }

  // Box Shadow
  const shadowTokens = tokens.filter(t => t.category === 'shadow');
  if (shadowTokens.length > 0) {
    lines.push('      boxShadow: {');
    for (const token of shadowTokens) {
      const key = token.name.replace('shadow-', '');
      lines.push(`        '${key}': '${token.value.value}',`);
    }
    lines.push('      },');
  }

  // Z-Index
  const zIndexTokens = tokens.filter(t => t.category === 'zIndex');
  if (zIndexTokens.length > 0) {
    lines.push('      zIndex: {');
    for (const token of zIndexTokens) {
      const key = token.name.replace('z-index-', '');
      lines.push(`        '${key}': '${token.value.value}',`);
    }
    lines.push('      },');
  }

  // Animation
  const durationTokens = tokens.filter(t => t.type === 'duration');
  if (durationTokens.length > 0) {
    lines.push('      transitionDuration: {');
    for (const token of durationTokens) {
      const key = token.name.replace('duration-', '');
      lines.push(`        '${key}': '${token.value.value}',`);
    }
    lines.push('      },');
  }

  // Screens (breakpoints)
  const breakpointTokens = tokens.filter(t => t.category === 'breakpoint');
  if (breakpointTokens.length > 0) {
    lines.push('      screens: {');
    for (const token of breakpointTokens) {
      const key = token.name.replace('breakpoint-', '');
      if (key !== 'xs') { // xs is usually not needed in Tailwind
        lines.push(`        '${key}': '${token.value.value}',`);
      }
    }
    lines.push('      },');
  }

  lines.push('    },');
  lines.push('  },');
  lines.push('};');

  return {
    format: 'tailwind',
    content: lines.join('\n'),
    filename: 'tailwind.config.js',
    mimeType: 'text/javascript',
  };
}

// =============================================================================
// iOS SWIFT TRANSFORMER
// =============================================================================

function transformToiOS(
  tokens: DesignToken[],
  options: TransformOptions
): TransformResult {
  const { colorScheme = 'light' } = options;
  const lines: string[] = [];

  lines.push('import SwiftUI');
  lines.push('');
  lines.push('// Design Tokens');
  lines.push('// Generated by Tailwind Builder');
  lines.push('');

  // Colors
  const colorTokens = tokens.filter(t => t.category === 'color');
  if (colorTokens.length > 0) {
    lines.push('extension Color {');
    lines.push('    struct DesignTokens {');

    for (const token of colorTokens) {
      const value = colorScheme === 'dark' && token.value.darkValue
        ? token.value.darkValue
        : token.value.value;

      if (typeof value === 'string' && value.startsWith('#')) {
        const rgb = hexToRgb(value);
        if (rgb) {
          const swiftName = camelCase(token.name);
          lines.push(`        static let ${swiftName} = Color(red: ${(rgb.r / 255).toFixed(3)}, green: ${(rgb.g / 255).toFixed(3)}, blue: ${(rgb.b / 255).toFixed(3)})`);
        }
      }
    }

    lines.push('    }');
    lines.push('}');
    lines.push('');
  }

  // Spacing
  const spacingTokens = tokens.filter(t => t.category === 'spacing');
  if (spacingTokens.length > 0) {
    lines.push('struct Spacing {');

    for (const token of spacingTokens) {
      const value = parseFloat(String(token.value.value));
      const pxValue = token.value.value.toString().includes('rem')
        ? value * 16
        : value;
      const swiftName = camelCase(token.name.replace('spacing-', 'space'));
      lines.push(`    static let ${swiftName}: CGFloat = ${pxValue}`);
    }

    lines.push('}');
    lines.push('');
  }

  // Typography
  const fontSizeTokens = tokens.filter(t => t.type === 'fontSize');
  if (fontSizeTokens.length > 0) {
    lines.push('struct Typography {');
    lines.push('    struct Size {');

    for (const token of fontSizeTokens) {
      const value = parseFloat(String(token.value.value));
      const ptValue = token.value.value.toString().includes('rem')
        ? value * 16
        : value;
      const swiftName = camelCase(token.name.replace('font-size-', ''));
      lines.push(`        static let ${swiftName}: CGFloat = ${ptValue}`);
    }

    lines.push('    }');
    lines.push('}');
    lines.push('');
  }

  // Border Radius
  const radiusTokens = tokens.filter(t => t.type === 'borderRadius');
  if (radiusTokens.length > 0) {
    lines.push('struct CornerRadius {');

    for (const token of radiusTokens) {
      if (token.value.value !== '9999px') {
        const value = parseFloat(String(token.value.value));
        const pxValue = token.value.value.toString().includes('rem')
          ? value * 16
          : value;
        const swiftName = camelCase(token.name.replace('border-radius-', ''));
        lines.push(`    static let ${swiftName}: CGFloat = ${pxValue}`);
      }
    }

    lines.push('}');
  }

  return {
    format: 'ios',
    content: lines.join('\n'),
    filename: 'DesignTokens.swift',
    mimeType: 'text/x-swift',
  };
}

// =============================================================================
// ANDROID XML TRANSFORMER
// =============================================================================

function transformToAndroid(
  tokens: DesignToken[],
  options: TransformOptions
): TransformResult {
  const { colorScheme = 'light' } = options;
  const lines: string[] = [];

  lines.push('<?xml version="1.0" encoding="utf-8"?>');
  lines.push('<!-- Design Tokens - Generated by Tailwind Builder -->');
  lines.push('<resources>');
  lines.push('');

  // Colors
  const colorTokens = tokens.filter(t => t.category === 'color');
  if (colorTokens.length > 0) {
    lines.push('    <!-- Colors -->');

    for (const token of colorTokens) {
      const value = colorScheme === 'dark' && token.value.darkValue
        ? token.value.darkValue
        : token.value.value;

      if (typeof value === 'string' && value.startsWith('#')) {
        const androidName = token.path.join('_') + '_' + token.name;
        const androidColor = value.length === 4
          ? `#${value[1]}${value[1]}${value[2]}${value[2]}${value[3]}${value[3]}`
          : value;
        lines.push(`    <color name="${androidName}">${androidColor}</color>`);
      }
    }
    lines.push('');
  }

  // Dimensions (spacing, font sizes, border radius)
  const dimensionTokens = tokens.filter(t =>
    t.category === 'spacing' ||
    t.type === 'fontSize' ||
    t.type === 'borderRadius'
  );

  if (dimensionTokens.length > 0) {
    lines.push('    <!-- Dimensions -->');

    for (const token of dimensionTokens) {
      const value = String(token.value.value);
      let dpValue: string;

      if (value.includes('rem')) {
        dpValue = `${parseFloat(value) * 16}dp`;
      } else if (value.includes('px')) {
        dpValue = `${parseFloat(value)}dp`;
      } else if (value === '9999px') {
        dpValue = '9999dp';
      } else {
        dpValue = `${parseFloat(value)}dp`;
      }

      const androidName = token.path.join('_') + '_' + token.name;
      lines.push(`    <dimen name="${androidName}">${dpValue}</dimen>`);
    }
    lines.push('');
  }

  // Integers (z-index, opacity as percentage, font weight)
  const integerTokens = tokens.filter(t =>
    t.category === 'zIndex' ||
    t.type === 'fontWeight'
  );

  if (integerTokens.length > 0) {
    lines.push('    <!-- Integers -->');

    for (const token of integerTokens) {
      const value = String(token.value.value);
      if (value !== 'auto') {
        const androidName = token.path.join('_') + '_' + token.name;
        lines.push(`    <integer name="${androidName}">${value}</integer>`);
      }
    }
    lines.push('');
  }

  // Strings (font family, easing)
  const stringTokens = tokens.filter(t =>
    t.type === 'fontFamily' ||
    t.type === 'easing' ||
    t.type === 'shadow'
  );

  if (stringTokens.length > 0) {
    lines.push('    <!-- Strings -->');

    for (const token of stringTokens) {
      const androidName = token.path.join('_') + '_' + token.name;
      const value = String(token.value.value).replace(/"/g, '\\"');
      lines.push(`    <string name="${androidName}">${escapeXml(value)}</string>`);
    }
    lines.push('');
  }

  lines.push('</resources>');

  return {
    format: 'android',
    content: lines.join('\n'),
    filename: 'design_tokens.xml',
    mimeType: 'application/xml',
  };
}

// =============================================================================
// MAIN TRANSFORMER
// =============================================================================

/**
 * Transform tokens to the specified format
 */
export function transformTokens(
  tokens: DesignToken[],
  options: TransformOptions
): TransformResult {
  // Filter by categories if specified
  let filteredTokens = tokens;
  if (options.categories && options.categories.length > 0) {
    filteredTokens = tokens.filter(t => options.categories!.includes(t.category));
  }

  switch (options.format) {
    case 'css':
      return transformToCSS(filteredTokens, options);
    case 'scss':
      return transformToSCSS(filteredTokens, options);
    case 'js':
      return transformToJS(filteredTokens, { ...options, typescript: false });
    case 'ts':
      return transformToJS(filteredTokens, { ...options, typescript: true });
    case 'json':
      return transformToJSON(filteredTokens, options);
    case 'figma':
      return transformToFigma(filteredTokens, options);
    case 'tailwind':
      return transformToTailwind(filteredTokens, options);
    case 'ios':
      return transformToiOS(filteredTokens, options);
    case 'android':
      return transformToAndroid(filteredTokens, options);
    default:
      throw new Error(`Unsupported format: ${options.format}`);
  }
}

/**
 * Transform entire token collection
 */
export function transformCollection(
  collection: TokenCollection,
  options: TransformOptions
): TransformResult {
  return transformTokens(collection.tokens, options);
}

/**
 * Transform tokens to all supported formats
 */
export function transformToAllFormats(
  tokens: DesignToken[],
  options: Omit<TransformOptions, 'format'>
): TransformResult[] {
  const formats: TokenFormat[] = [
    'css',
    'scss',
    'js',
    'ts',
    'json',
    'figma',
    'tailwind',
    'ios',
    'android',
  ];

  return formats.map(format => transformTokens(tokens, { ...options, format }));
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

function groupTokensByPath(tokens: DesignToken[]): Record<string, DesignToken[]> {
  const grouped: Record<string, DesignToken[]> = {};

  for (const token of tokens) {
    const pathKey = token.path.join('/');
    if (!grouped[pathKey]) {
      grouped[pathKey] = [];
    }
    grouped[pathKey].push(token);
  }

  return grouped;
}

function buildNestedObject(
  tokens: DesignToken[],
  colorScheme: ColorScheme
): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const token of tokens) {
    let current = result;

    for (const part of token.path) {
      if (!current[part]) {
        current[part] = {};
      }
      current = current[part] as Record<string, unknown>;
    }

    current[token.name] = colorScheme === 'dark' && token.value.darkValue
      ? token.value.darkValue
      : token.value.value;
  }

  return result;
}

function buildColorObject(
  tokens: DesignToken[],
  colorScheme: ColorScheme
): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const token of tokens) {
    const value = colorScheme === 'dark' && token.value.darkValue
      ? token.value.darkValue
      : token.value.value;

    // Handle nested colors (e.g., gray.500)
    const pathWithoutCategory = token.path.slice(1); // Remove 'color'
    let current = result;

    for (const part of pathWithoutCategory) {
      if (part === 'primitive' || part === 'semantic') continue;
      if (!current[part]) {
        current[part] = {};
      }
      current = current[part] as Record<string, unknown>;
    }

    // Extract shade from name (e.g., gray-500 -> 500)
    const nameParts = token.name.split('-');
    const shade = nameParts[nameParts.length - 1];

    if (/^\d+$/.test(shade)) {
      current[shade] = value;
    } else {
      current[token.name] = value;
    }
  }

  return result;
}

function formatObjectContent(obj: Record<string, unknown>, indent: number): string {
  const lines: string[] = [];
  const spaces = ' '.repeat(indent);

  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'object' && value !== null) {
      lines.push(`${spaces}'${key}': {`);
      lines.push(formatObjectContent(value as Record<string, unknown>, indent + 2));
      lines.push(`${spaces}},`);
    } else {
      lines.push(`${spaces}'${key}': '${value}',`);
    }
  }

  return lines.join('\n');
}

function mapTypeToFigma(type: string): string {
  const typeMap: Record<string, string> = {
    color: 'color',
    fontSize: 'fontSizes',
    fontFamily: 'fontFamilies',
    fontWeight: 'fontWeights',
    lineHeight: 'lineHeights',
    letterSpacing: 'letterSpacing',
    spacing: 'spacing',
    borderRadius: 'borderRadius',
    borderWidth: 'borderWidth',
    shadow: 'boxShadow',
    opacity: 'opacity',
    duration: 'motion',
    easing: 'motion',
    dimension: 'sizing',
  };

  return typeMap[type] || 'other';
}

function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  const shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
  const expandedHex = hex.replace(shorthandRegex, (_, r, g, b) => r + r + g + g + b + b);

  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(expandedHex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : null;
}

function camelCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, char) => char.toUpperCase())
    .replace(/^(.)/, (_, char) => char.toLowerCase());
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// =============================================================================
// FORMAT METADATA
// =============================================================================

export interface FormatInfo {
  id: TokenFormat;
  name: string;
  extension: string;
  description: string;
  icon: string;
}

export const formatInfo: FormatInfo[] = [
  { id: 'css', name: 'CSS', extension: '.css', description: 'CSS Custom Properties', icon: 'css' },
  { id: 'scss', name: 'SCSS', extension: '.scss', description: 'Sass Variables', icon: 'sass' },
  { id: 'js', name: 'JavaScript', extension: '.js', description: 'JavaScript Module', icon: 'javascript' },
  { id: 'ts', name: 'TypeScript', extension: '.ts', description: 'TypeScript Module', icon: 'typescript' },
  { id: 'json', name: 'JSON', extension: '.json', description: 'Style Dictionary Format', icon: 'json' },
  { id: 'figma', name: 'Figma', extension: '.json', description: 'Figma Tokens Format', icon: 'figma' },
  { id: 'tailwind', name: 'Tailwind', extension: '.config.js', description: 'Tailwind CSS Config', icon: 'tailwind' },
  { id: 'ios', name: 'iOS Swift', extension: '.swift', description: 'SwiftUI Extensions', icon: 'swift' },
  { id: 'android', name: 'Android', extension: '.xml', description: 'Android Resources', icon: 'android' },
];

export function getFormatInfo(format: TokenFormat): FormatInfo | undefined {
  return formatInfo.find(f => f.id === format);
}
